spring:
  jpa:
    show-sql: true
  cache:
    type: none
  application:
    name: sia
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/postgres
server:
  servlet:
    context-path: /api/v1
  port: 8010
